####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CFLAGS = -g -O2 -Wall -D_XUTILS_DEBUG -D_XUTILS_USE_GNU -D_ASSERT_TIMED -D_XUTILS_DEBUG
CFLAGS += -I./src/crypt -I./src/data -I./src/net -I./src/sys -I./src
NAME = libxutils.a
LIBS = -lpthread
ODIR = ./build
OBJ = o

ifeq ($(XUTILS_USE_SSL),y)
CFLAGS += -D_XUTILS_USE_SSL
LIBS += -lssl -lcrypto
endif

OBJS = addr.$(OBJ) \
	aes.$(OBJ) \
	api.$(OBJ) \
	array.$(OBJ) \
	base64.$(OBJ) \
	buf.$(OBJ) \
	cli.$(OBJ) \
	cpu.$(OBJ) \
	crc32.$(OBJ) \
	crypt.$(OBJ) \
	event.$(OBJ) \
	hash.$(OBJ) \
	hmac.$(OBJ) \
	http.$(OBJ) \
	json.$(OBJ) \
	jwt.$(OBJ) \
	list.$(OBJ) \
	log.$(OBJ) \
	map.$(OBJ) \
	md5.$(OBJ) \
	mdtp.$(OBJ) \
	mon.$(OBJ) \
	ntp.$(OBJ) \
	pool.$(OBJ) \
	rsa.$(OBJ) \
	rtp.$(OBJ) \
	srch.$(OBJ) \
	sha1.$(OBJ) \
	sha256.$(OBJ) \
	sig.$(OBJ) \
	sock.$(OBJ) \
	str.$(OBJ) \
	sync.$(OBJ) \
	thread.$(OBJ) \
	type.$(OBJ) \
	ws.$(OBJ) \
	xfs.$(OBJ) \
	xtime.$(OBJ) \
	xver.$(OBJ)

OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
INSTALL_INC = /usr/local/include/xutils
INSTALL_BIN = /usr/local/lib
VPATH = ./src:./src/sys:./src/net:./src/data:./src/crypt

.c.$(OBJ):
	@test -d $(ODIR) || mkdir -p $(ODIR)
	$(CC) $(CFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(AR) rcs -o $(ODIR)/$(NAME) $(OBJECTS)

.PHONY: install
install:
	@test -d $(INSTALL_BIN) || mkdir -p $(INSTALL_BIN)
	install -m 0755 $(ODIR)/$(NAME) $(INSTALL_BIN)/
	@test -d $(INSTALL_INC) || mkdir -p $(INSTALL_INC)
	cp -r ./src/crypt/*.h $(INSTALL_INC)/
	cp -r ./src/data/*.h $(INSTALL_INC)/
	cp -r ./src/net/*.h $(INSTALL_INC)/
	cp -r ./src/sys/*.h $(INSTALL_INC)/
	cp -r ./src/*.h $(INSTALL_INC)/

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
