####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CFLAGS = -g -O2 -Wall -D_XUTILS_DEBUG -D_XUTILS_USE_SSL -I./src -I./media
LIBS = -lpthread -lssl -lcrypto
NAME = libxutils.a
ODIR = ./obj
OBJ = o

OBJS = addr.$(OBJ) \
	array.$(OBJ) \
	crypt.$(OBJ) \
	errex.$(OBJ) \
	event.$(OBJ) \
	hash.$(OBJ) \
	http.$(OBJ) \
	jwt.$(OBJ) \
	list.$(OBJ) \
	mdtp.$(OBJ) \
	ntp.$(OBJ) \
	rtp.$(OBJ) \
	sock.$(OBJ) \
	sync.$(OBJ) \
	thread.$(OBJ) \
	ts.$(OBJ) \
	xaes.$(OBJ) \
	xapi.$(OBJ) \
	xbuf.$(OBJ) \
	xcli.$(OBJ) \
	xcpu.$(OBJ) \
	xfs.$(OBJ) \
	xjson.$(OBJ) \
	xlog.$(OBJ) \
	xmap.$(OBJ) \
	xstr.$(OBJ) \
	xtime.$(OBJ) \
	xtop.$(OBJ) \
	xtype.$(OBJ) \
	xver.$(OBJ)

OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
INSTALL_INC = /usr/local/include/xutils
INSTALL_BIN = /usr/local/lib
VPATH = ./src:./media

.c.$(OBJ):
	@test -d $(ODIR) || mkdir -p $(ODIR)
	$(CC) $(CFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(AR) rcs -o $(ODIR)/$(NAME) $(OBJECTS)

.PHONY: install
install:
	@test -d $(INSTALL_BIN) || mkdir -p $(INSTALL_BIN)
	@install -m 0755 $(ODIR)/$(NAME) $(INSTALL_BIN)/
	@test -d $(INSTALL_INC) || mkdir -p $(INSTALL_INC)
	@cp -r ./src/*.h $(INSTALL_INC)/
	@cp -r ./media/*.h $(INSTALL_INC)/

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
