name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CMAKE
      run: sudo apt install -y cmake

    - name: Install dependencies
      run: sudo apt install -y libssl-dev

    - name: Check versions
      run: |
        gcc --version
        cmake --version

    - name: Build with CMAKE
      run: |
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX=./libxutil && cmake --build build --target install

    - name: Uploading libxutils
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu_latest_libxutils
        path: ./libxutil
