name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CMake
      run: choco install cmake --version 3.31.0 --installargs 'ADD_CMAKE_TO_PATH=System' --no-progress

    - name: Install dependencies
      run: choco install openssl --no-progress

    - name: Check versions
      run: |
        gcc --version
        cmake --version

    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
